SafeNightOut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('accounts/signup/', views.signup, name='signup'),
    #CRUD for drink session
    path('drinksessions/', views.drinksession_index, name='index'),
    path('drinksessions/<int:session_id>/', views.drinksession_detail, name='detail'),
    path('drinksessions/create/', views.DrinksessionCreate.as_view(), name='drinksessions_create'),
    path('drinksessions/<int:pk>/update/', views.DrinksessionUpdate.as_view(), name='drinksessions_update'),
    path('drinksessions/<int:pk>/delete/', views.DrinksessionDelete.as_view(), name='drinksessions_delete'),
    #CRUD for drinks
    path('drinks/', views.DrinkList.as_view(), name='drinks_index'),
    path('drinks/<int:pk>/', views.DrinkDetail.as_view(), name='drinks_detail'),
    path('drinks/create/', views.DrinkCreate.as_view(), name='drinks_create'),
    path('drinks/<int:pk>/update/', views.DrinkUpdate.as_view(), name='drinks_update'),
    #might have to remove delete functionality, multiple users could use that drink
    path('drinks/<int:pk>/delete/', views.DrinkDelete.as_view(), name='drinks_delete'),
    # addings photoes to session
    path('drinksession/<int:session_id>/add_drink/', views.add_drink_time, name='add_drink_time'),
    path('drinksession/<int:session_id>/add_photo/', views.add_photo, name='add_photo'),
    path('profile/create/', views.ProfileCreate.as_view(), name='profile_create'),
    path('profile/<int:pk>/update/', views.ProfileUpdate.as_view(), name='profile_update'),
    path('laws/texas', views.laws_texas, name='laws_texas')
]


    

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import timedelta, datetime, date, time
import math

# Create your models here.
sexes = (
    ('M', 'male'),
    ('F', 'female'),
    ('O', 'other'),
)

drinks = (
    ('B', 'beer'),
    ('W', 'wine'),
    ('L', 'liquor'),
    ('C', 'cocktail'),
    ('S', 'spiked'),
)

ethanol_density = 789  # g/l
liver_detox_rate = .015 # g/dl/hr
bac_inteval = 15  # in minutes


def get_vol(drink_type):
    if drink_type == 'B':
        return 12
    if drink_type == 'W':
        return 5
    if drink_type == 'L':
        return 1.5
    if drink_type == 'C':
        return 5
    if drink_type == 'S':
        return 12


def calc_bac(curr_bac, min_passed, sex, weight, d=False):
    absorb_frac = .68 if sex == 'M' else .55
    absorb_weight = absorb_frac * weight * 454
    if d:
        vol = get_vol(d.drink_type)
        g_consumed = ethanol_density * vol * 29.57 * d.abv / 1000
        new_bac = g_consumed / absorb_weight * 100
        return new_bac + curr_bac
    return curr_bac  - liver_detox_rate * 100 / (60/min_passed)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    weight = models.IntegerField()
    sex = models.CharField(max_length=1, choices=sexes)

    def __str__(self):
        return f"{self.username}'s profile"

    def get_absolute_url(self):
        return reverse('index')


class Drink(models.Model):
    name = models.CharField(max_length=100)
    drink_type = models.CharField(max_length=100, choices=drinks)
    abv = models.IntegerField()  # default??? beer 5%, wine 12%, liquor 40%?
    cost = models.IntegerField()

    def get_absolute_url(self):
        return reverse('drinks_detail', kwargs={'pk': self.id})

    def __str__(self):
        return f"{self.name}"


class DrinkSession(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_time = models.DateField()
    # should this be integer field?? or maybe even calculated
    duration = models.IntegerField()

    def bac_info(self):
        bac_list = []  # can also make this dictionary
        # get drink events, NOTE: sorted in order at drinktime model
        drink_events = self.drinktime_set.all()
        if drink_events:
            # initialize bac list
            first_dt = drink_events[0].time_consumed
            # get first starting point divisible by time interval
            starting_minute = math.floor(
                first_dt.minute / bac_inteval)*bac_inteval
            start = drink_events[0].time_consumed.replace(
                second=0, minute=starting_minute)
            first_bac = [start, 0]
            bac_list.append(first_bac)
            # get user info
            w = self.user.profile.weight
            s = self.user.profile.sex

        # loop through drink events and add data to bac_dict
            for i in range(len(drink_events)):
                # append new drink
                new_time = datetime.combine(date.min, bac_list[-1][0]) + timedelta(minutes=bac_inteval)
                bac = calc_bac(bac_list[-1][1], bac_inteval, s, w, drink_events[i].drink)
                bac_list.append([new_time.time(),bac])

                # if not user's last drink
                if ((i+1) < len(drink_events)):
                    # countdown, reducing body's bac until user drinks again
                    while ((datetime.combine(date.min, drink_events[i+1].time_consumed)
                     - datetime.combine(date.min, bac_list[-1][0]))
                        > timedelta(minutes=bac_inteval)):
                        new_time = datetime.combine(date.min, bac_list[-1][0]) + timedelta(minutes=bac_inteval)
                        bac = calc_bac(bac_list[-1][1], bac_inteval, s, w)
                        bac = 0 if (bac<0) else bac 
                        bac_list.append([new_time.time(),bac])
            #after last drink, reducing body's bac until it reaches 0 
            while (bac_list[-1][1] > 0):
                new_time = datetime.combine(date.min, bac_list[-1][0]) + timedelta(minutes=bac_inteval)
                bac = calc_bac(bac_list[-1][1], bac_inteval, s, w)
                bac = 0 if (bac<0) else bac 
                bac_list.append([new_time.time(),bac])
        return bac_list

    def __str__(self):
        return f"drinking on {self.start_time}"

    def get_absolute_url(self):
        return reverse('detail', kwargs={'session_id': self.id})


class DrinkTime(models.Model):
    time_consumed = models.TimeField()
    effects = models.CharField(max_length=300)
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    session = models.ForeignKey(DrinkSession, on_delete=models.CASCADE)

    class Meta:
        ordering = ['time_consumed']


class Photo(models.Model):
    url = models.CharField(max_length=250)
    session = models.ForeignKey(DrinkSession, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for session_id: {self.session_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import DrinkTime, Drink, DrinkSession

class DrinkTimeForm(ModelForm):
  class Meta:
    model = DrinkTime
    fields = ['drink', 'effects','time_consumed']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import DrinkSession, Drink, Profile, Photo, DrinkTime
from .forms import DrinkTimeForm
from bokeh.embed import components
from bokeh.plotting import figure
import uuid
import boto3

S3_BASE_URL = 'https://s3-us-east-2.amazonaws.com/'
BUCKET = 'safenightout'


# Create your views here.
class DrinksessionCreate(CreateView):
    model = DrinkSession
    fields = ['start_time', 'duration']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DrinksessionUpdate(UpdateView):
    model = DrinkSession
    fields = ['start_time']


class DrinksessionDelete(DeleteView):
    model = DrinkSession
    success_url = '/drinksessions/'


def home(request):
    p = Profile.objects.all()
    return render(request, 'home.html', {'profile': p})

# about page

def about(request):
    return render(request, 'about.html')

def laws_texas(request):
    return render(request, 'laws/texas.html')

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('profile_create')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

@login_required 
def drinksession_index(request):

    session = DrinkSession.objects.filter(user=request.user)
    return render(request, 'drinksessions/index.html', {'session': session})

@login_required 
def drinksession_detail(request, session_id):

    if (DrinkSession.objects.get(id=session_id).user != request.user):
        return redirect('index')
    drink_time_form = DrinkTimeForm()
    # this pulls the list of BAC every 15minutes
    data = DrinkSession.objects.get(id=session_id).bac_info()
    # seperates the list of two value lists into two seperate lists
    d1 = [item[0] for item in data]
    d2 = [item[1] for item in data]
    # this defines the type of bokeh plot
    plot = figure(plot_width=300, plot_height=200, x_axis_type="datetime", x_axis_label="time", y_axis_label="Blood Alcohol Content (BAC)")
    # this customizes the x and y axis and color of lines
    plot.line(d1, d2,  color="blue", line_width=4)

    script, div = components(plot)

    return render(request, 'drinksessions/detail.html', {
        'session': DrinkSession.objects.get(id=session_id),
        'drink_time_form': drink_time_form,
        'drink_set': DrinkSession.objects.get(id=session_id).drinktime_set.all(),
        'script': script,
        'div': div
    })


class ProfileCreate(CreateView):
    model = Profile
    fields = ['first_name', 'last_name', 'sex', 'weight']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProfileUpdate(UpdateView):
    model = Profile
    fields = ['first_name', 'last_name', 'sex', 'weight']


class DrinkCreate(CreateView):
    model = Drink
    fields = '__all__'


class DrinkDelete(DeleteView):
    model = Drink
    success_url = '/drinks/'  # maybe drink session, maybe we remove drink delete


class DrinkUpdate(UpdateView):
    model = Drink
    fields = ['cost', 'abv', 'drink_type']


class DrinkList(ListView):
    model = Drink


class DrinkDetail(DetailView):
    model = Drink

@login_required 
def add_drink_time(request, session_id):

    form = DrinkTimeForm(request.POST)
    if form.is_valid():
        new_drink_time = form.save(commit=False)
        new_drink_time.session_id = session_id
        new_drink_time.save()
    return redirect('detail', session_id=session_id)

@login_required 
def add_photo(request, session_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, session_id=session_id)
            photo.save()
        except:
            print('An error occured uploading file to S3')
    return redirect('detail', session_id=session_id)

main_app/templates/drinksessions/detail.html
{% extends 'base.html' %}
{% block content %}




<h2 class = "center blue-text text-darken-4">{{session.user.profile.first_name}}'s details for {{session.start_time}}</h2>
{% if user.profile.id %}
<h1></h1>
{% else %}
<h6>Profile is needed to calculate your BAC</h6>
<a class='btn-large waves-effect waves-light' href = "{% url 'profile_create' %}">Create my Profile</a>
{% endif %} 
<br>
<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{session.start_time}}</span>
                <p>Duration: {{ session.duration }} minutes</p>
                <br>
                <br>
                <br>
                <div class = 'center row'>
                <a class='btn-large yellow darken-2 waves-effect waves-light'
                    href="{% url 'drinksessions_update' session.id %}">Update Session</a>
                <a class='btn-large red darken-2 waves-effect waves-light'
                    href="{% url 'drinksessions_delete' session.id %}">Delete Session</a>
                </div>
                <br>
                <h5 class = 'center blue-text text-darken-4'>BAC Graph</h5>
            </div>
            {{div | safe}}
        </div>
    {% for photo in session.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' session.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" class="btn" value="Upload Photo">
    </form>
    </div>
    <div class="col s6">
        <h5 class = 'center'>Add Drink To My Session</h5>
        <form action="{% url 'add_drink_time' session.id %}" method="post">
            {% csrf_token %}
            {{ drink_time_form.as_p }}
            <input type="submit" class="btn-large green left" value="Add Drink Event">
        </form>
        <br>
        <br>
        <br>

        <div>
        <h5 class = 'center blue-text text-darken-4'>This Session's Drinks</h5>

        <div class="row">
            <div class="col s24 m12">
                {% for d in drink_set %}
              <div class="card blue darken-4">
                <div class="card-content white-text">
                  <span class="card-title center">{{d.drink}}</span>
                  <p>Effects: {{d.effects}}</p>
                  <p>Time: {{d.time_consumed}}</p>
              </div>
            </div>
            {% endfor %}

          </div>
    </div>
</div>
    </div>
<script>
    // initialize the drink select
    var selectEl = document.getElementById('id_drink');
    M.FormSelect.init(selectEl);

    let timeEl = document.getElementById('id_time_consumed')
    M.Timepicker.init(timeEl, {
      format: "HH-MM",
      twelveHour: false,
      autoClose: true,
    })
</script>

{% endblock %}

main_app/templates/drinksessions/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class = 'center blue-text text-darken-4'>Welcome back, {{user.profile.first_name}} {{user.profile.last_name}}</h1>

<br>

<div class = 'index-container'>
<span class = 'center button-holder'>
{% if user.profile.first_name%}
<a class='btn-large waves-effect amber darken-3 waves-light' href = "{% url 'profile_update' user.profile.id  %}"><i class = 'material-icons right'>edit</i> Update my Profile</a>
{% else %}
<a class='btn-large waves-effect green waves-light' href = "{% url 'profile_create' %}">Create my Profile</a>
{% endif %} 



  <a class= 'btn-large blue darken-4 waves-effect waves-light' href="{% url 'drinksessions_create' %}"><i class='material-icons right'>add</i>Add a Session?</a>
</span>

<br>
<br>

{% for s in session %}
<div class = 'session-container'>

  <a href="{% url 'detail' s.id %}">
    <div class="card">
        <div class="card-content black-text">
            <span class="card-title">Date: {{ s.start_time }}</span>
            <p>Duration: {{ s.duration }} minutes</p>
            <br>
        </div>
    </div>
  </a>
  </div>
  
  <br>

{% endfor %}
</div>




{% endblock %}